name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_NAME: ${{ secrets.VERCEL_ORG_NAME }}
      VERCEL_PROJECT_NAME: ${{ secrets.VERCEL_PROJECT_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Verify Environment Variables
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then echo "VERCEL_TOKEN is not set"; else echo "VERCEL_TOKEN is set"; fi
          if [ -z "$VERCEL_ORG_NAME" ]; then echo "VERCEL_ORG_NAME is not set"; else echo "VERCEL_ORG_NAME is set"; fi
          if [ -z "$VERCEL_PROJECT_NAME" ]; then echo "VERCEL_PROJECT_NAME is not set"; else echo "VERCEL_PROJECT_NAME is set"; fi

      - name: Remove .vercel directory if exists
        run: |
          if [ -d ".vercel" ]; then rm -rf .vercel; fi

      - name: Link Vercel Project
        run: vercel link --yes --token $VERCEL_TOKEN --scope $VERCEL_ORG_NAME --project $VERCEL_PROJECT_NAME

      - name: Pull Vercel Environment Variables
        run: vercel env pull .env -y --environment=production --token $VERCEL_TOKEN

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: vercel --prod --token $VERCEL_TOKEN
